/*
    Program: airline.cpp
    Author: Son Huynh
    Lab Section: 04
    Date: 12/1/2013
    Purpose: This program can be used by an airline to sell tickets for seats on a commercial plane
    Algorithms:
        1. Prompt the user if they are a customer or an employee
        2. If they are a customer
            a. Display the seating chart
            b. Display the seating options
            c. Prompt the user to select a seating option
            d. Prompt the user if they want to select a seat or let the program do it
                e. If they select to choose their seat manually, prompt user to input row and column
                f. If their seat is take, output not available
                g. If their seat is available, display the price and ask if they want to book it
                h. If they want to book it, mark the seat as occupied, and display the total cost If no, still output the total cost
                    (However, if their row is 6, 7, 15, or 16, ask if they are over 18. Only 18 can book exit row seats)
                i. Display the updated seating chart

                j. If they select to let the program choose a seat, randomly generate a seat within the seating option range
                k. Output the seat randomly generated by the program and ask if they want to book it
                l. If they want to book it, mark the seat as occupied, and display the total cost. If no, still output the total cost
                    (However, if their row is 6, 7, 15, or 16, ask if they are over 18. Only 18 can book exit row seats)
                m. Display the updated seating chart
        3. If they are an employee
            a. Display the updated seating chart
            b. Count how many seats are available, and display the amount to the screen
            c. Count how many seats are booked, and display the amount to the screen
            d. Count how many seats are booked in First Class, and display the amount to the screen
            e. Count how many seats are booked in Business Class, and display the amount to the screen
            f. Count how many seats are booked in Economy Class, and display the amount to the screen
            g. Display the total revenue generated for the whole flight to the screen.
*/

#include <iostream>
#include <iomanip>
#include <ctime>
#include <cstdlib>

//Prototypes
void displaySeats(char seats[][7], int size);                                                           //Prototype for displaySeats
void displaySeatsEmployee(char seats[][7], int size, int total);                                                   //Prototype for displaySeatsEmployee

using namespace std;

int main()
{
    char seats[22][7];                                                                                  //Declaration
    int size = 22;
    char book;
    int choice;
    int classSelection;
    int row, column;
    char seatSelection;
    int randomRow, randomCol;
    char bookAgain, returnMenu;
    int total = 0;
    //int countAvailable = 0, countBooked = 0;
    //int countFirstClass = 0, countBusinessClass = 0, countEconomyClass = 0;
    int age;

    srand(time(0));

    for (int x = 0; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            seats[x][y] = '*';                                                                          //Initializing the array seats to empty
        }
    }

    do
    {
        cout << "Menu: ";                                                                               //Outputs menu
        cout << "\n1. Customer ";
        cout << "\n2. Employee ";
        cout << endl << endl;

        do
        {
            cout << "Enter 1 for customer and 2 for employee: ";                                        //Inputs choice
            cin >> choice;
        }
        while (!(choice >= 1 && choice <= 2));

        switch (choice)
        {
            case 1:
                do
                {
                    displaySeats(seats, size);                                                          //Calling displaySeats function

                    cout << endl;
                    cout << "\nSeating Options: ";                                                      //Display menu
                    cout << "\n1. First Class (Row 1-4)";
                    cout << "\n2. Business Class (Row 5-8)";
                    cout << "\n3. Economy Class (Row 9-22)";
                    cout << endl << endl;

                    do
                    {
                        cout << "Enter your selection: ";                                               //Input classSelection
                        cin >> classSelection;
                    }
                    while (!(classSelection >= 1 && classSelection <= 3));


                    cout << "\nTo choose your seat, press Y. Otherwise, press any key: ";               //Input seatSelection
                    cin >> seatSelection;
                    seatSelection = toupper(seatSelection);

                    if (classSelection == 1 && seatSelection == 'Y')
                    {
                        cout << "\nTo select the seat you desire ";
                        cout << endl;

                        do
                        {
                            cout << "Enter the row (1-4): ";                                            //Input the row of the seat
                            cin >> row;
                        }
                        while (!(row >= 1 && row <= 4));

                        do
                        {
                            cout << "Enter the column (1-7): ";                                         //Input the column of the seat
                            cin >> column;
                        }
                        while (!(column >= 1 && column <= 7));

                        if (seats[row-1][column-1] == 'X')
                        {
                            cout << "\nThis seat is not available. ";                                   //Outputs seat is not available
                        }


                        if (seats[row-1][column-1] == '*')
                        {
                            cout << "\nThis seat is available for $3600. ";
                            cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";         //Input if user wants to book
                            cin >> book;
                            book = toupper(book);

                            if (book == 'Y')
                            {
                                total += 3600;                                                          //Increases total cost by 3600 if they book
                                seats[row-1][column-1] = 'X';                                           //If seat is available, changes it to occupied
                                cout << "\nYour seat has been booked. ";                                //Outputs that the seat has been booked
                                cout << "\nTOTAL COST: $"<<total;                                       //Outputs total
                            }

                            if (book != 'Y')
                                cout << "\nTOTAL COST: $"<<total;                                       //Outputs total
                        }

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    if (classSelection == 1 && seatSelection != 'Y')
                    {
                        bool repeat;

                        do
                        {
                            randomRow = rand() % 4 + 1;                                                 //Randomly generates a seat in first class section
                            randomCol = rand() % 7 + 1;

                            if (seats[randomRow-1][randomCol-1] == '*')
                            {
                                repeat = false;

                                cout << "The seat selected by the program is at Row "<<randomRow<<", Col "<<randomCol;

                                cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";     //Input if user wants to book
                                cin >> book;
                                book = toupper(book);

                                if (book == 'Y')
                                {
                                    total += 3600;                                                      //Increases total cost by 3600 if they book
                                    seats[randomRow-1][randomCol-1] = 'X';                              //If seat is available, changes it to occupied
                                    cout << "\nYour seat has been booked. ";                            //Outputs that the seat has been booked
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total
                                }

                                if (book != 'Y')
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total

                                break;
                            }

                            if (seats[randomRow-1][randomCol-1] == 'X')
                                repeat = true;
                        }
                        while (repeat == true);                                                         //Keeps repeating until a new seat is found

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    if (classSelection == 2 && seatSelection == 'Y')
                    {
                        cout << "\nTo select the seat you desire ";
                        cout << endl;

                        do
                        {
                            cout << "Enter the row (5-8): ";                                            //Input the row of the seat
                            cin >> row;
                        }
                        while (!(row >= 5 && row <= 8));

                        do
                        {
                            cout << "Enter the column (1-7): ";                                         //Input the column of the seat
                            cin >> column;
                        }
                        while (!(column >= 1 && column <= 7));

                        if (seats[row-1][column-1] == 'X')
                        {
                            cout << "\nThis seat is not available. ";                                   //Outputs seat is not available
                        }


                        if (seats[row-1][column-1] == '*')
                        {
                            cout << "\nThis seat is available for $1500. ";
                            cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";         //Input if user wants to book
                            cin >> book;
                            book = toupper(book);

                            if (book == 'Y')
                            {
                                if (row - 1 == 5 || row - 1 == 6)
                                {
                                    cout << "\nThis is an exit row. Enter your age: ";                  //If the row is an exit row (6-7), ask for age
                                    cin >> age;

                                    if (age >= 18)
                                    {
                                        total += 1500;                                                  //Increases total cost by 1500 if they book
                                        seats[row-1][column-1] = 'X';                                   //If seat is available, changes it to occupied
                                        cout << "\nYour seat has been booked. ";                        //Outputs that the seat has been booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }

                                    if (age < 18)
                                    {
                                        cout << "\nYou cannot book this seat ";                         //Outputs seat cannot be booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }
                                }

                                if (row - 1 != 5 && row - 1 != 6)
                                {
                                    total += 1500;                                                      //Increases total cost by 1500 if they book
                                    seats[row-1][column-1] = 'X';                                       //If seat is available, changes it to occupied
                                    cout << "\nYour seat has been booked. ";                            //Outputs that the seat has been booked
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total
                                }
                            }

                            if (book != 'Y')
                                cout << "\nTOTAL COST: $"<<total;                                       //Outputs total
                        }

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    if (classSelection == 2 && seatSelection != 'Y')
                    {
                        bool repeat;

                        do
                        {
                            randomRow = rand() % 4 + 5;                                                 //Randomly generates a seat in first class section
                            randomCol = rand() % 7 + 1;

                            if (seats[randomRow-1][randomCol-1] == '*')
                            {
                                repeat = false;

                                cout << "The seat selected by the program is at Row "<<randomRow<<", Col "<<randomCol;

                                cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";     //Input if user wants to book
                                cin >> book;
                                book = toupper(book);

                                if (book == 'Y')
                                {
                                    if (randomRow - 1 == 5 || randomRow - 1 == 6)
                                    {
                                        cout << "\nThis is an exit row. Enter your age: ";              //If the row is an exit row (6-7), ask for age
                                        cin >> age;

                                        if (age >= 18)
                                        {
                                            total += 1500;                                              //Increases total cost by 1500 if they book
                                            seats[randomRow-1][randomCol-1] = 'X';                      //If seat is available, changes it to occupied
                                            cout << "\nYour seat has been booked. ";                    //Outputs that the seat has been booked
                                            cout << "\nTOTAL COST: $"<<total;                           //Outputs total
                                        }
                                        if (age < 18)
                                        {
                                            cout << "\nYou cannot book this seat ";                     //Outputs seat cannot be booked
                                            cout << "\nTOTAL COST: $"<<total;                           //Outputs total
                                        }
                                    }

                                    if (randomRow - 1 != 5 && randomRow - 1 != 6)
                                    {
                                        total += 1500;
                                        seats[randomRow-1][randomCol-1] = 'X';                          //If seat is available, changes it to occupied
                                        cout << "\nYour seat has been booked. ";                        //Outputs that the seat has been booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }
                                }

                                if (book != 'Y')
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total

                                break;
                            }

                            if (seats[randomRow-1][randomCol-1] == 'X')
                                repeat = true;
                        }
                        while (repeat == true);                                                         //Keeps repeating until a new seat is found

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    if (classSelection == 3 && seatSelection == 'Y')
                    {
                        cout << "\nTo select the seat you desire ";
                        cout << endl;

                        do
                        {
                            cout << "Enter the row (9-22): ";                                           //Input the row of the seat
                            cin >> row;
                        }
                        while (!(row >= 9 && row <= 22));

                        do
                        {
                            cout << "Enter the column (1-7): ";                                         //Input the column of the seat
                            cin >> column;
                        }
                        while (!(column >= 1 && column <= 7));

                        if (seats[row-1][column-1] == 'X')
                        {
                            cout << "\nThis seat is not available. ";                                   //Outputs seat is not available
                        }


                        if (seats[row-1][column-1] == '*')
                        {
                            cout << "\nThis seat is available for $550. ";
                            cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";         //Input if user wants to book
                            cin >> book;
                            book = toupper(book);

                            if (book == 'Y')
                            {
                                if (row - 1 == 14 || row - 1 == 15)
                                {
                                    cout << "\nThis is an exit row. Enter your age: ";                  //If the row is an exit row (15-16), ask for age
                                    cin >> age;

                                    if (age >= 18)
                                    {
                                        total += 550;                                                   //Increases total cost by 550 if they book
                                        seats[row-1][column-1] = 'X';                                   //If seat is available, changes it to occupied
                                        cout << "\nYour seat has been booked. ";                        //Outputs that the seat has been booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }

                                    if (age < 18)
                                    {
                                        cout << "\nYou cannot book this seat ";                         //Outputs seat cannot be booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }
                                }

                                if (row - 1 != 14 && row - 1 != 15)
                                {
                                    total += 550;                                                       //Increases total cost by 550 if they book
                                    seats[row-1][column-1] = 'X';                                       //If seat is available, changes it to occupied
                                    cout << "\nYour seat has been booked. ";                            //Outputs that the seat has been booked
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total
                                }
                            }

                            if (book != 'Y')
                                cout << "\nTOTAL COST: $"<<total;                                       //Outputs total
                        }

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    if (classSelection == 3 && seatSelection != 'Y')
                    {
                        bool repeat;

                        do
                        {
                            randomRow = rand() % 14 + 9;                                                 //Randomly generates a seat in first class section
                            randomCol = rand() % 7 + 1;

                            if (seats[randomRow-1][randomCol-1] == '*')
                            {
                                repeat = false;

                                cout << "The seat selected by the program is at Row "<<randomRow<<", Col "<<randomCol;

                                cout << "\n\nEnter Y to book the seat. Otherwise, press any key: ";     //Input if user wants to book
                                cin >> book;
                                book = toupper(book);

                                if (book == 'Y')
                                {
                                    if (randomRow - 1 == 14 || randomRow - 1 == 15)
                                    {
                                        cout << "\nThis is an exit row. Enter your age: ";
                                        cin >> age;

                                        if (age >= 18)
                                        {
                                            total += 550;                                               //Increases total cost by 550 if they book
                                            seats[randomRow-1][randomCol-1] = 'X';                      //If seat is available, changes it to occupied
                                            cout << "\nYour seat has been booked. ";                    //Outputs that the seat has been booked
                                            cout << "\nTOTAL COST: $"<<total;                           //Outputs total
                                        }
                                        if (age < 18)
                                        {
                                            cout << "\nYou cannot book this seat ";                     //Outputs seat cannot be booked
                                            cout << "\nTOTAL COST: $"<<total;                           //Outputs total
                                        }
                                    }

                                    if (randomRow - 1 != 14 && randomRow - 1 != 15)
                                    {
                                        total += 550;
                                        seats[randomRow-1][randomCol-1] = 'X';                          //If seat is available, changes it to occupied
                                        cout << "\nYour seat has been booked. ";                        //Outputs that the seat has been booked
                                        cout << "\nTOTAL COST: $"<<total;                               //Outputs total
                                    }
                                }

                                if (book != 'Y')
                                    cout << "\nTOTAL COST: $"<<total;                                   //Outputs total

                                break;
                            }

                            if (seats[randomRow-1][randomCol-1] == 'X')
                                repeat = true;
                        }
                        while (repeat == true);                                                         //Keeps repeating until a new seat is found

                        cout << endl;
                        displaySeats(seats, size);                                                      //Calling displaySeats function
                    }

                    cout << endl;
                    cout << "\nTo book another seat, press Y. Otherwise, press any key: ";              //To return to main menu, press Y
                    cin >> bookAgain;
                    bookAgain = toupper(bookAgain);

                    if (bookAgain == 'Y')
                        system("CLS");

                    if (bookAgain != 'Y')
                        cout << "\nFINAL COST: $"<<total;                                               //Outputs total

                    cout << endl;
                }
                while (bookAgain == 'Y');

                break;

            case 2:
                displaySeatsEmployee(seats, size, total);                                                              //Calling displaySeats function

                break;

        }

        cout << "\nTo return to the main menu, press Y. Otherwise, press any key: ";                    //To return to main menu, press Y
        cin >> returnMenu;
        returnMenu = toupper(returnMenu);

        if (returnMenu == 'Y')
            system("CLS");

        if (returnMenu != 'Y')
            cout << "\nThank you for choosing us! ";                                                    //Outputs total

        cout << endl;
    }
    while (returnMenu == 'Y');

}

/*
    Function: displaySeats
    Purpose: To display the seating chart
    Parameters: seats[][7] represents the 2D seats array, while size represents the row value needed for the array
    Return: None
*/
void displaySeats(char seats[][7], int size)
{
    int countFirstClassAvai = 0, countBusinessClassAvai = 0, countEconomyClassAvai = 0;
    int countAvailablePlane = 0, countBookedPlane = 0;
    int rows[22] = {0};

    cout << endl;
    cout << "SEATING CHART: " << endl;

    for (int x = 0; x < size; x++)
    {
        cout << endl;
        cout << "Row "<<x+1<< ": "<<setw(3);                                                //Outputs Row titles

        if (x < 9)
            cout << " ";

        for (int y = 0; y < 7; y++)
        {
            cout << seats[x][y] << " ";                                                     //Outputs the seats
        }
    }

    cout << "\n\nLegend: ";
    cout << "\n* - Available ";
    cout << "\nX - Occupied ";
    cout << endl;

    for (int x = 0; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')                                                         //Counting seats available
                countAvailablePlane ++;

            if (seats[x][y] == 'X')                                                         //Counting seats booked
                countBookedPlane ++;
        }
    }

    for (int x = 0; x < 4; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')
                countFirstClassAvai ++;                                                     //Counting seats booked in First Class
        }
    }

    for (int x = 4; x < 8; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')
                countBusinessClassAvai ++;                                                  //Counting seats booked in Business Class
        }
    }

    for (int x = 8; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')
                countEconomyClassAvai ++;                                                   //Counting seats booked in Economy Class
        }
    }

    for (int x = 0; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')                                                         //Counting seats available
                rows[x] ++;
        }
    }

    cout << endl;
    cout << endl << countAvailablePlane <<" seats available on the plane. ";                //Outputs seats available
    cout << endl << countBookedPlane <<" seats booked on the plane. ";                      //Outputs seats booked
    cout << endl;
    cout << endl << countFirstClassAvai <<" seats available in First Class. ";              //Outputs seats available in First Class
    cout << endl << countBusinessClassAvai <<" seats available in Business Class. ";        //Outputs seats available in Business Class
    cout << endl << countEconomyClassAvai <<" seats available in Economy Class. ";          //Outputs seats available in Economy Class
    cout << endl;

    for (int x = 0; x < 22; x++)
    {
        cout << "\nRow "<<x+1<< " has "<<setw(3);

        if (x < 9)
            cout << " ";

        cout <<rows[x]<<" empty seats. ";                                                   //Outputs the amount of empty seats per row
    }
}


/*
    Function: displaySeatsEmployee
    Purpose: To display the seating chart, but information for employees only
    Parameters: seats[][7] represents the 2D seats array, while size represents the row value needed for the array
    Return: None
*/
void displaySeatsEmployee(char seats[][7], int size, int total)
{
    int countAvailable = 0, countBooked = 0;
    int countFirstClass = 0, countBusinessClass = 0, countEconomyClass = 0;

    cout << endl;
    cout << "UPDATED SEATING CHART: " << endl;

    for (int x = 0; x < size; x++)
    {
        cout << endl;
        cout << "Row "<<x+1<< ": "<<setw(3);                                                //Outputs Row titles

        if (x < 9)
            cout << " ";

        for (int y = 0; y < 7; y++)
        {
            cout << seats[x][y] << " ";                                                     //Outputs the seats
        }
    }

    cout << "\n\nLegend: ";
    cout << "\n* - Available ";
    cout << "\nX - Occupied ";
    cout << endl;

    for (int x = 0; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == '*')                                                         //Counting seats available
                countAvailable ++;

            if (seats[x][y] == 'X')                                                         //Counting seats booked
                countBooked ++;
        }
    }

    for (int x = 0; x < 4; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == 'X')
                countFirstClass ++;                                                         //Counting seats booked in First Class
        }
    }

    for (int x = 4; x < 8; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == 'X')
                countBusinessClass ++;                                                      //Counting seats booked in Business Class
        }
    }

    for (int x = 8; x < 22; x++)
    {
        for (int y = 0; y < 7; y++)
        {
            if (seats[x][y] == 'X')
                countEconomyClass ++;                                                       //Counting seats booked in Economy Class
        }
    }

    cout << "\n\nREPORT: ";
    cout << endl;
    cout << endl << countAvailable <<" seats available. ";                                  //Outputs seats available
    cout << endl << countBooked <<" seats booked. ";                                        //Outputs seats booked
    cout << endl;
    cout << endl << countFirstClass <<" seats booked in First Class. ";                     //Outputs seats booked in First Class
    cout << endl << countBusinessClass <<" seats booked in Business Class. ";               //Outputs seats booked in Business Class
    cout << endl << countEconomyClass <<" seats booked in Economy Class. ";                 //Outputs seats booked in Economy Class
    cout << endl;
    cout << "\nTotal money generated for the entire flight: $"<<total;                      //Outputs total money generated
    cout << endl << endl;
}
